# Generated by Django 2.0 on 2019-07-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20190717_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
